export const DISPATCH_KATEGORI = "DISPATCH_KATEGORI";
export const EDIT_KATEGORI = "EDIT_KATEGORI";
export const DELETE_KATEGORI = "DELETE_KATEGORI";
export const DISPATCH_JENIS = "DISPATCH_JENIS";
export const EDIT_JENIS = "EDIT_JENIS";
export const DELETE_JENIS = "DELETE_JENIS";
