export const DISPATCH_BARANG = "DISPATCH_BARANG";
export const EDIT_BARANG = "EDIT_BARANG";
export const DELETE_BARANG = "DELETE_BARANG";
export const DISPATCH_CATALOGUE = "DISPATCH_CATALOGUE";
export const EDIT_CATALOGUE = "EDIT_CATALOGUE";
export const DELETE_CATALOGUE = "DELETE_CATALOGUE";
